# known handles not found in cve parsed data
KNOWN_ACK_TWITTER_HANDLES = { 
  'yuki chen' : 'guhe120',
 'zhiniang peng' : 'edwardzpeng',
 'mateusz jurczyk' : 'j00ru',
 'james forshaw' : 'tiraniddo',
 'xuefeng li' : 'lxf02942370',
 'david erceg' : 'david_erceg',
 'khalil zhani' : 'Khalil_Zhani',
 'lokihardt' : 'lokihardt',
 'kdot' : None,
 'qixun zhao' : 'S0rryMybad',
 'jun kokatsu' : 'shhnjk',
 'guang gong' : 'oldfresher',
 'miaubiz' : 'miaubiz',
 'ashar javed' : 'soaj1664ashar',
 'k0shl' : 'KeyZ3r0',
 'fangming gu' : 'afang5472',
 'dhanesh kizhakkinan' : 'dhanesh_k',
 'steven seeley' : 'steventseeley',
 'zhong_sf' : 'zhong_sf',
 'yangkang' : 'dnpushme',
 'huynh phuoc' : 'hph0var',
 'hossein lotfi' : 'hosselot',
 'pgboy' : 'pgboy',
 'jarvis_1oop' : 'baixia4',
 'nicolas joly' : 'n_joly',
 'abdelhamid naceri' : 'KLINIX5',
 'atte kettunen' : 'attekett',
 'sergei glazunov' : None,
 'gal de' : 'galdeleon',
 'ivan fratric' : 'ifsecure',
 'zimi' : 'YHZX_2013',
 'william' : None,
 'the chromium' : None,
 'microsoft platform' : None,
 'ke liu' : 'klotxl404',
 'shefang zhong' : None,
 'rgod' : 'rgod',
 'rob wu' : None,
 'jeongoh kyea' : 'kkokkokye',
 'microsoft chakracore' : None,
 'jinquan' : 'jq0904',
 'anonymous researcher' : None,
 'mr_me' : 'steventseeley',
 'cloudfuzzer' : None,
 'willj' : None,
 'zhangjie' : None,
 'bee13oy' : 'bee13oy',
 'haifei li' : 'HaifeiLi',
 'peter hlavaty' : 'rezer0dai',
 'wayne low' : 'x9090',
 'bar lahav' : None,
 'jaanus kääp' : 'JaanusKaap',
 'jungu' : 'Bl1nnnk',
 'hao li' : None,
 'keqi hu' : None,
 'bl1nnnk' : 'bl1nnnk',
 'masato kinugawa' : 'kinugawamasato',
 'adlab' : None,
 'wenxu wu' : 'ma7h1as',
 'leecraso' : 'leecraso',
 'aki helin' : None,
 'hardik shah' : 'hardik05',
 'polar bear' : None,
 'liu long' : None,
 'luan herrera' : 'lbherrera_',
 'mariusz mlynski' : None,
 'fortinet’s fortiguard' : None,
 'jinquan(@jq0904)' : 'jq0904',
 'omair' : None,
 'abdulrahman alqabandi' : 'Qab',
 'guopengfei' : None,
 'moonliang' : None,
 'natalie silvanovich' : 'natashenka',
 'zhe jin' : None,
 'tao yan' : 'Ga1ois',
 'fanxiaocao' : 'TinySecEx',
 'le huu' : 'linhlhq',
 'rskvp93' : 'rskvp93',
 'simon zuckerbraun' : None,
 'william s&#246;derberg' : 'kwsecu',
 'lucas leong' : '_wmliang_',
 'pham van' : 'rskvp93',
 'claudio bozzato' : None,
 'zhang wangjunjie' : 'hillstone_lab',
 'anonymous finder' : None,
 'arthur gerkis' : 'ax330d',
 'axel souchet' : '0vercl0k',
 'jordan rabet' : None,
 'nan wang' : 'eternalsakura13',
 'sergey glazunov' : None,
 'marcin wiazowski' : None,
 'netanel ben' : None,
 'man yue' : None,
 'ranchoice' : 'zhanlulab',
 'hillstone network' : None,
 'netanel ben-simon' : None,
 'oleksandr mirosh' : 'olekmirosh',
 'skylined' : None,
 'tencent keen' : None,
 'zhihua yao' : 'hackyzh',
 'hyungseok han' : 'daramg_h',
}


