# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: check-version

on:
  workflow_dispatch:
      
permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Install cvedata
      run: pip install .
    - name: Get cvedata python-version
      id: cvedata_ver
      run: echo "CVEDATA_VER=v$(python -m cvedata.version)" >> $GITHUB_OUTPUT
    - name: output ver
      run: echo "${{ steps.cvedata_ver.outputs.CVEDATA_VER }}"

