# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Release and Publish

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
      
# permissions:
#   contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Install cvedata
      run: pip install .
    - name: Get cvedata python-version
      id: cvedata_ver
      run: echo "CVEDATA_VER=v$(python -m cvedata.version)" >> $GITHUB_OUTPUT

    - name: Update CVE data
      run: |        
        python -m cvedata.update        
    - name: Print Stats
      run: |        
        python -m cvedata
        ls -rotah cvedata/data/
    - name: Zip Generated Data
      run: |
        cd cvedata/data/.cache
        zip -r ../../../cvedata_cache.zip * -x winbindex\*
        cd ../../..
        cd cvedata/data
        zip -r ../../cvedata_data.zip * -x .cache\* .placeholder
        cd ../..

    # - name: Publish package
    #   uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_API_TOKEN }}
    
    # Upload Artifacts if failure
    - name: Upload Build Dir
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cvedata-build
        path: |
          cvedata/data/*.json
          cvedata/data/*.json.gz
          cvedata/data/.cache/kb_csv/*.csv
          cvedata/data/.cache/msrc_cvrfs/*.json
          cvedata/data/.cache/*.json.gz
          cvedata/data/.cache/*.json
          dist/
        retention-days: 3
    
    - name: Release on GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cache_data.zip
          cvedata_data.zip
          cvedata/data/metadata.json
          ./dist/*
        tag_name: "${{ steps.cvedata_ver.outputs.CVEDATA_VER }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
